// <auto-generated />
using MagnisStockExchange;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace MagnisStockExchange.Migrations
{
    [DbContext(typeof(StockExchangeContext))]
    [Migration("20180419171441_Changed_StockExchange_Table")]
    partial class Changed_StockExchange_Table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Entity.StockExchangeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateTime");

                    b.Property<long>("Price");

                    b.Property<string>("Symbol");

                    b.Property<int>("Volume");

                    b.HasKey("Id");

                    b.ToTable("StockExchange");
                });
#pragma warning restore 612, 618
        }
    }
}
